### ISSUE TITLE
Cancelling the Highlight Colour menu crashes the program

### ISSUE THREAD

**Issue by Beniial** [Sambo3975/SMBX2-Tileset-Creator#1]
**Describe the bug**
The program will crash when pressing cancel on the highlight colour menu

**To Reproduce**
1. Load an image
2. Click "Select Color" for Highlight Color to bring up the colour selection panel
3. Click Cancel

**Expected behavior**
The program to return to the main window and use the previously selected colour

**Error Traceback**
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1885, in __call__
  File "widgets.py", line 24, in load_color_data
  File "tkinter\__init__.py", line 1639, in configure
  File "tkinter\__init__.py", line 1629, in _configure
_tkinter.TclError: unknown color name "None"

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Sambo3975** [comment]
Aw, man! I encountered this error during testing, but I forgot to fix it. Added to my TODO for the hotfix.

**Comment by Sambo3975** [comment]
Fixed in the next release.
