### ISSUE TITLE
Request: Define ID range

### ISSUE THREAD

**Issue by spoonybardol** [Sambo3975/SMBX2-Tileset-Creator#11]
**Is your feature request related to a problem? Please describe.**
Not a problem or bug so much as mitigating the most tedious part of exporting tilesets with this software. It already cuts out most of the tedium, but manually assigning IDs if you want fine control over them and don't just want them to start at the very top or very bottom of the list is the slowest part of the process.

**Describe the solution you'd like**
Give an option to input a starting ID number and select if you want the software to assign IDs ascending or descending starting from that number. So, say, using 751 as your starting point with ascending selected it would assign IDs 751, 752, 753, etc.

**Describe alternatives you've considered**
Manually entering each number? Again, tedious. 

**Additional context**

**Comment by Sambo3975** [comment]
This is already supported, though.

If you want to start at 751 and assign IDs in an ascending order from there, you can enter `751-1291` into the "Block IDs" box (1291 is currently the highest used block ID), and make sure "IDs High to Low" is unchecked. Alternatively, you can select "User Slots" from the dropdown, which selects IDs from the `751-1000` ID range.

If you want to start at 751 and assign IDs in a descending order from there, you can enter `1-751` into the "Block IDs" box and check the "IDs High to Low" box.

If you want IDs from multiple ranges, you can enter something like `1-100;120-140` and it will select IDs from both.

The same goes for "BGO IDs".

I'm sorry if this feature was not clear to you and you ended up wasting time. It is explained in the tooltips for those options. I may need to add more detail to the README.

**Comment by spoonybardol** [comment]
Ohhhh, geez, ok yeah. When I saw 'Avoid Special' was the default selection in that setting I just assumed it was a binary choice between skipping special tiles and not. That's my bad for not looking closer at all the options. Perhaps it could be clarified a bit, but since this feature is already present I guess this can be closed!
