### ISSUE TITLE
Make the program generate .ini files for blocks and bgos

### ISSUE THREAD

**Issue by Murphmario** [Sambo3975/SMBX2-Tileset-Creator#12]
Because there's no .ini file when exporting graphics, the generated graphics won't have a proper preview image in Moondust. Implementation should be simple enough since the program already generates .ini files for the tileset.

**Comment by Sambo3975** [comment]
Are you referring to the editor, or the game engine? It _sounds_ like you're talking about the editor, but I can't be certain.

The editor handles configurations set in TXT files just fine, so there's no reason to generate INIs in addition to them. Wohl confirmed this, and I found no issues during testing. If something isn't displaying properly in the editor, can you be more specific? Which properties don't work right?

I don't know if the engine itself handles TXTs properly, but I didn't make this with the engine in mind. The engine has different names for some properties in SMBX, and it also adds several more configurations that SMBX does not support, so it's not really that "simple" to do, as it would mean generating different configs depending on the engine you're exporting for, and, probably adding several more options for the engine to my software's UI.

**Comment by Murphmario** [comment]
> 
> 
> Are you referring to the editor, or the game engine? It _sounds_ like you're talking about the editor, but I can't be certain.
> 
> The editor handles configurations set in TXT files just fine, so there's no reason to generate INIs in addition to them. Wohl confirmed this, and I found no issues during testing. If something isn't displaying properly in the editor, can you be more specific? Which properties don't work right?
> 
> I don't know if the engine itself handles TXTs properly, but I didn't make this with the engine in mind. The engine has different names for some properties in SMBX, and it also adds several more configurations that SMBX does not support, so it's not really that "simple" to do, as it would mean generating different configs depending on the engine you're exporting for, and, probably adding several more options for the engine to my software's UI.

I'm talking about the editor. If generating blocks using the user IDs, then the blocks display the placeholder image for custom blocks (Custom.png) instead of the intended graphics, and also sets the size of the blocks to that image as well (I.E. 2x2 blocks would be rendered as 1x1 in the editor). Fix is simple, just generate a .ini file with the preview image set to the block id when generating a block in the user IDs.

**Comment by Sambo3975** [comment]
Oh, right. Those. I actually forgot about that bit with the 751-1000 range needing the image name defined. I'll make sure to address this with the next release. Although, why Wohl hasn't made this automatic is beyond me.

**Comment by Sambo3975** [comment]
This has been added in the next release. However, no INIs will be generated as PGE/Moondust supports setting the tile image in the TXTs. In the next release, you should see `image = block-xx.png` or `image = background-xx.png` on the first line of TXT files generated for tiles in the 751-1000 range.
