### ISSUE TITLE
Crash when exporting

### ISSUE THREAD

**Issue by Halzk** [Sambo3975/SMBX2-Tileset-Creator#13]
**Describe the bug**
When I try to export a tileset, it automatically crashes, I checked if all the id were correct, and they are. Don't know where this is coming from. 

**Error Traceback** 
```
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1885, in __call__
  File "main.py", line 460, in file_export
  File "tile.py", line 398, in export
  File "PIL\Image.py", line 2169, in save
PermissionError: [Errno 13] Permission denied: 'C:/Users/thema/Pictures/Sprite/tile fixing/background-800.png'
```

**Desktop**
OS: Windows 10

**Comment by Sambo3975** [comment]
It looks like a permission issue with your PC. Try the following:
1) Run the program as an administrator
2) Move your tileset image somewhere else and try exporting again.

**Comment by Sambo3975** [comment]
Closed due to inactivity.
