### ISSUE TITLE
'Export' crashes the application

### ISSUE THREAD

**Issue by MarioTheGre** [Sambo3975/SMBX2-Tileset-Creator#19]
**Describe the bug**
Exporting crashes the application.

**To Reproduce**
1. Go to 'File'
2. Click on 'Export'
3. See error

**Expected behavior**
You get to export the tileset to SMBX2.

**Error Traceback**
It only happened once. Might need a way to make the app more stable.

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by Sambo3975** [comment]
This doesn't provide sufficient info to reproduce the error, so there's not really anything I can do for you.
