### ISSUE TITLE
Crash when entering an invalid value into a textbox.

### ISSUE THREAD

**Issue by MegaDood11** [Sambo3975/SMBX2-Tileset-Creator#3]
**Describe the bug**

**To Reproduce**
1. Open an image
2. Click on 'Grid Size' or 'Pixel Scale' and manually enter a value (instead of pressing the drop down menu)
3. Enter a value that is not an integer

**Expected behavior**
Simply expected nothing to be entered, rather than crash.

**Error Traceback**
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1885, in __call__
  File "main.py", line 767, in redraw_canvas
  File "main.py", line 748, in _redraw_tileset_image
ValueError: invalid literal for int() with base 10: '3a'

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Sambo3975** [comment]
Will be fixed in the next release.

**Comment by Sambo3975** [comment]
Fixed in the next release.
