### ISSUE TITLE
Feature Request: Moving to image around to make tiles fit into their gridspace

### ISSUE THREAD

**Issue by MegaDood11** [Sambo3975/SMBX2-Tileset-Creator#4]
**Is your feature request related to a problem? Please describe.**
I'm not sure if this is something I'm missing, but oftentimes when trying to rip a spritesheet, there's usually part of a tile overlapping with the next gridspace, or a tile doesn't take up the entire gridspace. This for example:
![Imgur](https://i.imgur.com/UfRr4PW.png)

**Describe the solution you'd like**
Perhaps there could be an option to adjust the image's position relative to the grid? So if a tile is not taking up the entire gridspace, and the rest of it takes up part of the gridspace next to it, then maybe the image could be moved to adjust the position of a tile. Since this will affect the entire image however, as everything would be moving along with it, maybe there could be an option to save certain tiles before this change takes place? 

**Describe alternatives you've considered**
Maybe the image can be broken up into sections that can be moved around individually, so if part of an image sits nicely in a gridspace, the rest of the image could be split from this part and moved separately. After saving however everything would still part of the same tileset, just that some parts of the image have been moved around in the tileset importer. Again, I'm not sure if there's already a way to fix this as I couldn't find one, but this is my suggestion. Hope you like it!

**Comment by Sambo3975** [comment]
The ability to move portions of the image around sounds like it would add too much complexity to the UI, so I won't be adding your suggestion as it stands. However, I am willing to add features so sheets like this one can be supported.

From the image you showed, it looks like this is what's needed:

1. Changing the grid between tile placements (This is already supported, but is not enough on its own).
2. Tile Padding: adding spaces between grid squares (This is planned for a future release).
3. Grid Offsets: options to offset the grid in the x or y direction (Was not planned, but will be added to the list of planned features).

**Comment by Sambo3975** [comment]
Updated the OP to have the image imbedded

**Comment by Sambo3975** [comment]
Added in the next release.
