### ISSUE TITLE
Scroll Bar for large tilesets

### ISSUE THREAD

**Issue by MegaDood11** [Sambo3975/SMBX2-Tileset-Creator#5]
**Is your feature request related to a problem? Please describe.**
Sometimes when loading a very large tileset, it fails to display the entire image with a larger pixel scale. It would be really helpful if there was a way to scroll down to the image to select certain tiles.

**Describe the solution you'd like**
A scroll bar on the side of the screen if the tileset is larger than the main window so the user can scroll down to properly view the entire thing.

**Describe alternatives you've considered**
Not too sure what else could be used otherwise, but maybe an option to adjust the window tab?

**Comment by Alucard648** [comment]
Issue confirmed.
![scrolbar](https://user-images.githubusercontent.com/7596025/119272807-90d04900-bc10-11eb-8833-38d7a85f2a70.png)

**Comment by Sambo3975** [comment]
This is something that should for sure be added. Added to the list of planned features.

(I don't understand why you'd put all your tilesets into one image like that, though.)

**Comment by Sambo3975** [comment]
This has been added in the next release.
