### ISSUE TITLE
Apparent Oversight in the selection menu.

### ISSUE THREAD

**Issue by MegaDood11** [Sambo3975/SMBX2-Tileset-Creator#6]
**Describe the bug**
A mix up of Block Behaviour descriptions. Hovering over the 'P-Switch-able' option displays nothing, and hovering over the 'Lava' option displays the P-Switch-able option.

**To Reproduce**
1. Select a tile
2. Hover over the 'P-Switch-able' or 'Lava' options
3. Mistake in their descriptions

**Expected behavior**
Expected the lava option to describe how the block would one-shot players and NPCs, and for the P-Switch-able message to display on the P-Switch-able option.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
![image](https://user-images.githubusercontent.com/73924042/119261399-99c61800-bc1a-11eb-9075-0849d8fc1932.png)

**Comment by Sambo3975** [comment]
Nice catch! Will be fixed.

**Comment by Sambo3975** [comment]
Fixed in the next release.
