### ISSUE TITLE
Option to fix misalignments caused by margins between tiles in sheet

### ISSUE THREAD

**Issue by Alucard648** [Sambo3975/SMBX2-Tileset-Creator#7]
**Is your feature request related to a problem? Please describe.**
Opened random tilesheet with this tool and got this:
![misalignment](https://user-images.githubusercontent.com/7596025/119269206-295dcd80-bbff-11eb-85a4-e410eb1ee621.png)
Of course, I could set grid size to 17, but it would still yield an unusable tileset.

**Describe the solution you'd like**
Option to offset each tile to align with magins in sheet.
![Bg-choco-Castillo2](https://user-images.githubusercontent.com/7596025/119269382-1992b900-bc00-11eb-95fc-330f2917906b.png)
Credit goes to SuperAlex for this tile sheet.

**Comment by Sambo3975** [comment]
This feature is already planned. Be sure to check the Planned features section at the bottom of the README before requesting features.

**Comment by Sambo3975** [comment]
Added in the next release.
